# Regularization in Linear Regression

Regularization is a technique used in linear regression to prevent overfitting by adding a penalty term to the cost function. It discourages the model from fitting the training data too closely and helps in creating simpler models that generalize well to new, unseen data.

<img src="https://frenzy86.s3.eu-west-2.amazonaws.com/python/elastic.png" width=1200 >


## Lasso Regression (L1 Regularization)

Lasso regression adds the absolute values of the coefficients as a penalty term to the cost function. The formula for Lasso regression is:

$J(\theta) = \frac{1}{2m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})^2 + \lambda \sum_{j=1}^{n} |\theta_j|$

- $J(\theta) $: Cost function.
- m: Number of training examples.
- $h_\theta(x^{(i)})$: Hypothesis function.
- $y^{(i)}$: Actual output for the ith example.
- $\theta_j$: Coefficients/weights.
- $\lambda$: Regularization parameter.

The key characteristic of Lasso is that it tends to shrink some coefficients to exactly zero, effectively performing feature selection.

## Ridge Regression (L2 Regularization)

Ridge regression adds the squared values of the coefficients as a penalty term to the cost function. The formula for Ridge regression is:

$J(\theta) = \frac{1}{2m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})^2 + \lambda \sum_{j=1}^{n} \theta_j^2 $

The term \( \lambda \sum_{j=1}^{n} \theta_j^2 \) penalizes large coefficients, but unlike Lasso, Ridge does not lead to sparsity; all features contribute to the model, although with smaller weights.

## Elastic Net (L1+L2)

Elastic Net is a combination of L1 and L2 regularization. It adds both the absolute values and squared values of the coefficients to the cost function. The formula for Elastic Net is a combination of the Lasso and Ridge terms:

$ J(\theta) = \frac{1}{2m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})^2 + \lambda_1 \sum_{j=1}^{n} |\theta_j| + \lambda_2 \sum_{j=1}^{n} \theta_j^2 $

- $ \lambda_1 $: L1 regularization parameter.
- $ \lambda_2 $: L2 regularization parameter.

Elastic Net provides a balance between Lasso and Ridge, combining the feature selection property of Lasso with the robustness to multicollinearity offered by Ridge.


### Quando usare cosa?

- Ridge: quando pensi che molte variabili siano rilevanti
- Lasso: quando vuoi interpretabilità e selezione automatica delle variabili
- Elastic Net: il compromesso tra i due

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [48]:
#path = "boston_houses.csv"
path = "https://frenzy86.s3.eu-west-2.amazonaws.com/IFAO/boston_houses.csv"

data = pd.read_csv(path)
data.rename(columns={'MEDV': 'Price'}, inplace=True)
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0


In [49]:
## STEP1 DEFINIZIONE DI INPUT E OUTPUT
target = 'Price'
X = data.drop(columns=[target])
y = data[target]

In [50]:
## STEP2 TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=667,
                                                   )

In [51]:
## STEP3 MODELLAZIONE (REGRESSION)
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [52]:
## STEP4 PREDIZIONE
y_pred = model.predict(X_test)

In [53]:
## STEP5 VERIFICA METRICHE (for Regression)
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error,mean_squared_error

r2 = r2_score(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print(f'R2 score {r2}')
print(f'MSE score {mse}')
print(f'MAE score {mae}')
print(f'RMSE score {rmse}')

R2 score 0.6113097827490298
MSE score 34.48551396483906
MAE score 3.6837720318116567
RMSE score 5.872436799561069


In [72]:
from sklearn.model_selection import cross_val_score

r2_score = cross_val_score(model, X, y, scoring='r2', cv=5)
r2_score
#np.mean(r2_score)

array([ 0.63919994,  0.71386698,  0.58702344,  0.07923081, -0.25294154])

In [57]:
model.coef_

array([-8.78070834e-02,  4.43465741e-02,  2.95271430e-03,  1.26617246e+00,
       -1.24943692e+01,  4.30123121e+00, -8.68537481e-03, -1.38083562e+00,
        2.90347909e-01, -1.58071807e-02, -9.11768904e-01,  8.57061442e-03,
       -4.95272478e-01])

## Lasso L1 Regularization

The hyperparameter alpha controls the strength of the regularization. The grid search is performed to find the best value of alpha based on negative mean squared error, and then the model is fitted with the best alpha. Finally, the cross-validated R2 score is calculated and printed.

In [64]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso

lasso = Lasso()

parameters = {'alpha': [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20]}
lasso_regressor = GridSearchCV(lasso, 
                               parameters, 
                               scoring='neg_mean_squared_error', 
                               cv = 5,
                               )
lasso_regressor.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1,
                                   5, 10, 20]},
             scoring='neg_mean_squared_error')

In [65]:
lasso_regressor.best_params_

{'alpha': 0.001}

In [66]:
lasso_regressor.best_score_

np.float64(-19.52830832881595)

In [67]:
y_pred = lasso_regressor.predict(X_test)


In [68]:
## STEP5 VERIFICA METRICHE (for Regression)
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error,mean_squared_error

r2 = r2_score(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print(f'R2 score {r2}')
print(f'MSE score {mse}')
print(f'MAE score {mae}')
print(f'RMSE score {rmse}')

R2 score 0.6108064143863823
MSE score 34.530173994675444
MAE score 3.685060014294258
RMSE score 5.876238081857767


In [71]:
r2_score = cross_val_score(lasso_regressor, X, y, scoring='r2', cv=5)
r2_score
#np.mean(r2_score)

array([0.56156843, 0.63385562, 0.33456629, 0.08005313, 0.27459294])

## Ridge L2 Regularization

In [76]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge


ridge = Ridge()

parameters = {'alpha': [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20]}

ridge_regressor = GridSearchCV(ridge, 
                               parameters,
                               scoring='neg_mean_squared_error', 
                               cv=5,
                               )
ridge_regressor.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1,
                                   5, 10, 20]},
             scoring='neg_mean_squared_error')

In [77]:
ridge_regressor.best_params_

{'alpha': 0.01}

In [78]:
ridge_regressor.best_score_

np.float64(-19.5282035659934)

In [79]:
y_pred = ridge_regressor.predict(X_test)

In [80]:
## STEP5 VERIFICA METRICHE (for Regression)
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error,mean_squared_error

r2 = r2_score(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print(f'R2 score {r2}')
print(f'MSE score {mse}')
print(f'MAE score {mae}')
print(f'RMSE score {rmse}')

R2 score 0.6111673793936175
MSE score 34.498148326816164
MAE score 3.684087831476582
RMSE score 5.873512435231253


In [81]:
r2_score = cross_val_score(ridge, X, y, scoring='r2', cv=5)
r2_score
#np.mean(r2_score)

array([ 0.66089569,  0.74094893,  0.62923672,  0.08530169, -0.17029513])

## ElasticNet (L1+L2)

 Elastic Net is a linear regression model that combines both L1 (Lasso) and L2 (Ridge) regularization. Here's an example of how you can perform hyperparameter tuning using Elastic Net with scikit-learn's ElasticNet and GridSearchCV:

In [88]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import cross_val_score
import numpy as np

elastic_net = ElasticNet()

alpha_values = [1e-15, 1e-10, 1e-8, 1e-4, 1e-3, 1e-2, 1, 5, 10, 20]
l1_ratio_values = [0.1, 0.3, 0.5, 0.7, 0.9]

parameters = {'alpha': alpha_values, 
              'l1_ratio': l1_ratio_values,
              }

elastic_net_regressor = GridSearchCV(elastic_net, 
                                     parameters, 
                                     scoring='neg_mean_squared_error', 
                                     cv=5,
                                     )
elastic_net_regressor.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1,
                                   5, 10, 20],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]},
             scoring='neg_mean_squared_error')

In [89]:
elastic_net_regressor.best_estimator_

ElasticNet(alpha=0.001, l1_ratio=0.1)

In [93]:
elastic_net_regressor.best_params_

{'alpha': 0.001, 'l1_ratio': 0.1}

In [92]:
elastic_net_regressor.best_score_

np.float64(-19.511286467416642)

In [95]:
y_pred = elastic_net_regressor.predict(X_test)

In [96]:
## STEP5 VERIFICA METRICHE (for Regression)
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error,mean_squared_error

r2 = r2_score(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print(f'R2 score {r2}')
print(f'MSE score {mse}')
print(f'MAE score {mae}')
print(f'RMSE score {rmse}')

R2 score 0.6074645372898024
MSE score 34.82667322251288
MAE score 3.6934688443067665
RMSE score 5.901412815802067


In [97]:
r2_score = cross_val_score(elastic_net, X, y, scoring='r2', cv=5)
r2_score

array([0.57022044, 0.6626767 , 0.40322405, 0.45880379, 0.26833761])

In [98]:
r2_score.mean()

np.float64(0.4726525191941059)